import { ArrowLeft, ArrowRight, Check, LogIn, LogOut, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function AuthPage() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  return <div className="auth-page"><div className="auth-page__glow auth-page__glow--one" /><div className="auth-page__glow auth-page__glow--two" /><Link href="/" className="auth-back"><ArrowLeft size={15} /> Back to Nixesis</Link><main className="auth-card"><div className="auth-brand"><div className="brand__mark"><Sparkles size={20} /></div><span>NIXESIS</span><em>25</em></div>{isAuthenticated && user ? <><div className="auth-card__eyebrow"><span className="eyebrow__dot" />SESSION ACTIVE</div><h1>Good to see you, {user.name?.split(" ")[0] || "friend"}.</h1><p className="auth-card__intro">Your private arc is synced. You can now share progress, join competitions, and receive alerts from your circle.</p><div className="auth-account"><div className="settings-avatar">{(user.name || "NX").slice(0, 2).toUpperCase()}</div><div><strong>{user.name || "Nixesis member"}</strong><span>{user.email || "Signed in with Manus"}</span></div><ShieldCheck size={18} /></div><div className="auth-actions"><Link href="/" className="primary-button">Open dashboard <ArrowRight size={15} /></Link><button className="secondary-button" disabled={loading} onClick={() => void logout()}><LogOut size={15} /> {loading ? "Signing out…" : "Sign out"}</button></div></> : <><div className="auth-card__eyebrow"><span className="eyebrow__dot" />YOUR PRIVATE ARC</div><h1>Show up with people who get it.</h1><p className="auth-card__intro">Sign in to save your habits, share progress with friends, organise friendly competitions, and keep your next step close.</p><div className="auth-perks"><div><span><Check size={14} /></span><p><strong>Save your rhythm</strong><small>Habits and streaks follow you across sessions.</small></p></div><div><span><Users size={14} /></span><p><strong>Share by choice</strong><small>Only accepted friends can see your progress.</small></p></div><div><span><ShieldCheck size={14} /></span><p><strong>Private by design</strong><small>Your data stays scoped to your account.</small></p></div></div><button className="auth-login" onClick={() => startLogin()} disabled={loading}><LogIn size={17} /> {loading ? "Checking session…" : "Continue with Manus"}</button><p className="auth-note">No public profile is created until you choose to connect with someone.</p></>}</main></div>;
}
